=== iwonagg/StoryGraphPhD/json_validation/json_schema/schemas/archived_schema/schema_updated_20220120.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://www.ztg.fais.uj.edu.pl/",
    "title": "StoryGraph",
    "description": "JSON Schema for productions.",
    "type": "array",
    "definitions": {
        "node": {
            "type": "object",
            "anyOf": [
                {"required": ["Name"]},
                {"required": ["Id"]}
            ],
            "properties": {
                "Name": {"type": "string"}, 
                "Id": {"type": "string"},
                "Comment": {"type": "string"},
                "IsObject": {"type": "boolean"},
                "Characters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                },
                "Items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                },
                "Narration": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                },
                "Connections": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "Destination": {"type": "string"},
                            "Attributes": {
                                "type": "object",
                                "patternProperties": {
                                    "^.*$": {
                                        "anyOf": [
                                            {"type": "string"},
                                            {"type": "boolean"},
                                            {"type": "integer"},
                                            {"type": "number"},
                                            {"type": "null"}
                                        ]
                                    }
                                },
                                "additionalProperties": false
                            }
                        },
                        "additionalProperties": false,
                        "required": ["Destination"]
                    }
                },
                "Attributes": {
                    "type": "object",
                    "patternProperties": {
                        "^.*$": {
                        "anyOf": [
                            {"type": "string"},
                            {"type": "boolean"},
                            {"type": "integer"},
                            {"type": "number"},
                            {"type": "null"}
                        ]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "items": {
        "type": "object",
        "properties": {
            "Title": {"type": "string"},
            "TitleGeneric": {"type": "string"},
            "Description": {"type": "string"},
            "Override": {"type": "integer", "enum": [0, 1]},
            "Comment": {"type": "string"},
            "LSide": {
                "type": "object",
                "properties": {
                    "Locations": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {"$ref": "#/definitions/node"}
                            ]
                        }
                    }
                },
                "additionalProperties": false,
                "required": ["Locations"]
            },
            "RSide": {
                "type": "object",
                "properties": {},
                "additionalProperties": false
            },
            "Preconditions": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "type": "object",
                            "properties": {
                                "Cond": {"type": "string"}
                            },
                            "additionalProperties": false,
                            "required": ["Cond"]
                        }, 
                        {
                            "type": "object",
                            "required": ["Count"],
                            "anyOf": [
                                {"required": ["Min"]},
                                {"required": ["Max"]},
                                {"required": ["Min", "Max"]}
                            ],
                            "properties": {
                                "Count": {"type": "string"},
                                "Min": {"type": "number"},
                                "Max": {"type": "number"}
                            },
                            "additionalProperties": false
                        }
                    ]
                }
            },
            "Instructions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "Op": {"type": "string", "enum": ["create", "delete", "move", "set", "unset", "add", "mul", "winning"]},
                        "In": {"type": "string"},
                        "To": {"type": "string"},
                        "Attribute": {"type": "string"},
                        "Expr": {"type": "string"},
                        "Value": {
                            "anyOf": [
                                {"type": "string"},
                                {"type": "boolean"},
                                {"type": "integer"},
                                {"type": "number"},
                                {"type": "null"}
                            ]    
                        },                    
                        "Characters": {"type": "string", "enum": ["prohibit", "move"]},
                        "Items": {"type": "string", "enum": ["prohibit", "move"]},
                        "Sheaf": {"type": "object"}
                    },
                    "allOf": [
                        {
                            "if": {"properties": {"Op": { "enum": ["set"] }}},
                            "then": { 
                                "required": ["Attribute"],
                                "anyOf": [
                                    {"required": ["Value"]},
                                    {"required": ["Expr"]}
                                ]
                             }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["add"] }}},
                            "then": { "required": ["Attribute", "Value"] }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["mul"] }}},
                            "then": { "required": ["Attribute", "Value"] }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["delete"] }}},
                            "then": { 
                                "anyOf": [
                                    {"required": ["Node"]},
                                    {"required": ["Nodes"]}
                                ],
                                "properties": {
                                    "Node": {"type": "string"},
                                    "Nodes": {"type": "string"}
                                }
                            }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["create"] }}},
                            "then": { 
                                "required": ["In"],
                                "anyOf": [
                                    {"required": ["Node"]},
                                    {"required": ["Sheaf"]}
                                ],
                                "properties": {
                                    "Node": {"$ref": "#/definitions/node"}
                                }
                            }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["move"] }}},
                            "then": { 
                                "required": ["To"],
                                "anyOf": [
                                    {"required": ["Node"]},
                                    {"required": ["Nodes"]}
                                ],
                                "properties": {
                                    "Node": {"type": "string"},
                                    "Nodes": {"type": "string"}
                                }
                            }
                        }
                    ]
                },
                "additionalProperties": false,
                "required": ["Op"]
            }
        },
        "additionalProperties": false,
        "required": ["Title", "TitleGeneric", "Description", "LSide", "RSide", "Instructions", "Override"]
    }
}

=== iwonagg/StoryGraphPhD/api_get_random_world_json/worlds/rumcajs-world_pl.json
[
	{
	  "Title": "World around Jiczyn / Świat wokół Jiczyna",
	  "TitleGeneric": "",
	  "Description": "Świat, w którym może wydarzyć się misja Rumcajsa.",
	  "Override": 0,
	  "LSide": {
		"Locations": [
		{
			"Name": "Jaskinia",
			"Connections": [ { "Destination": "M23" } ],
			"Characters": [ { "Name": "Hanka" } ]
		}, {
			"Name": "Jiczyn",
			"Connections": [ { "Destination": "M31" } ],
			"Characters": [
				{ "Name": "Handlarz" },
				{ "Name": "Jubiler" }
			]
		}, {
			"Id": "M11",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M12" },
				{ "Destination": "M21" }
			]
		}, {
			"Id": "M12",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M11" },
				{ "Destination": "M13" },
				{ "Destination": "M22" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "M13",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M12" },
				{ "Destination": "M14" },
				{ "Destination": "M23" }
			]
		}, {
			"Id": "M14",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M13" },
				{ "Destination": "M24" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "M21",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M11" },
				{ "Destination": "M22" },
				{ "Destination": "M31" }
			]
		}, {
			"Id": "M22",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M12" },
				{ "Destination": "M21" },
				{ "Destination": "M23" },
				{ "Destination": "M32" }
			]
		}, {
			"Id": "M23",
			"Name": "Las",
			"Connections": [
				{ "Destination": "Jaskinia" },
				{ "Destination": "M13" },
				{ "Destination": "M22" },
				{ "Destination": "M24" },
				{ "Destination": "M33" }
			],
			"Characters": [ { "Name": "Rumcajs" } ],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "M24",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M14" },
				{ "Destination": "M23" },
				{ "Destination": "M34" }
			]
		}, {
			"Id": "M31",
			"Name": "Las",
			"Connections": [
				{ "Destination": "Jiczyn" },
				{ "Destination": "M21" },
				{ "Destination": "M32" },
				{ "Destination": "M41" }
			]
		}, {
			"Id": "M32",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M22" },
				{ "Destination": "M31" },
				{ "Destination": "M33" },
				{ "Destination": "M42" }
			]
		}, {
			"Id": "M33",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M23" },
				{ "Destination": "M32" },
				{ "Destination": "M34" },
				{ "Destination": "M43" }
			]
		}, {
			"Id": "M34",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M24" },
				{ "Destination": "M33" },
				{ "Destination": "M44" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "M41",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M31" },
				{ "Destination": "M42" }
			]
		}, {
			"Id": "M42",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M32" },
				{ "Destination": "M41" },
				{ "Destination": "M43" }
			]
		}, {
			"Id": "M43",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M33" },
				{ "Destination": "M42" },
				{ "Destination": "M44" }
			]
		}, {
			"Id": "M44",
			"Name": "Las",
			"Connections": [
				{ "Destination": "M34" },
				{ "Destination": "M43" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}
	]
},
"RSide": {},
"Instructions": []
}
]

=== iwonagg/StoryGraphPhD/api_get_random_world_json/worlds/rumcajs-world_Nantes.json
[
    {
        "Title": "World around Jiczyn for paper / Świat wokół Jiczyna do artykułu",
        "TitleGeneric": "",
        "Description": "Świat, w którym może wydarzyć się misja Rumcajsa.",
        "Override": 0,
        "LSide": {
            "Locations": [
                {
                    "Id": "140557505853056",
                    "Name": "Cave",
                    "Characters": [
                        {
                            "Name": "Manka",
                            "Attributes": {
                                "HP": 100
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140557505855168"
                        }
                    ]
                },
                {
                    "Id": "140557505855232",
                    "Name": "Jiczyn",
                    "Characters": [
                        {
                            "Name": "Merchant",
                            "Attributes": {
                                "HP": 100,
                                "Money": 10
                            }
                        },
                        {
                            "Name": "Jeweler",
                            "Attributes": {
                                "HP": 100,
                                "Money": 10
                            },
                            "Items": [
                                {
                                    "Name": "Necklace",
                                    "Attributes": {"Value": 1}
                                }
                            ]
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140557505868032"
                        }
                    ]
                },
                {
                    "Id": "140557505852928",
                    "Name": "Forest",
                    "Items": [
                        {
                            "Name": "Brushwood",
                            "Attributes": {
                                "Value": 1
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140557505854528"
                        },
                        {
                            "Destination": "140557505853824"
                        }
                    ]
                },
                {
                    "Id": "140557505854528",
                    "Name": "Forest",
                    "Connections": [
                        {
                            "Destination": "140557505852928"
                        },
                        {
                            "Destination": "140557505867904"
                        },
                        {
                            "Destination": "140557505855168"
                        }
                    ]
                },
                {
                    "Id": "140557505867904",
                    "Name": "Forest",
                    "Items": [
                        {
                            "Name": "Brushwood",
                            "Attributes": {
                                "Value": 1
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140557505854528"
                        },
                        {
                            "Destination": "140557505852992"
                        }
                    ]
                },
                {
                    "Id": "140557505853824",
                    "Name": "Forest",
                    "Connections": [
                        {
                            "Destination": "140557505852928"
                        },
                        {
                            "Destination": "140557505855168"
                        },
                        {
                            "Destination": "140557505868224"
                        }
                    ]
                },
                {
                    "Id": "140557505855168",
                    "Name": "Forest",
                    "Characters": [
                        {
                            "Name": "Rumcajs",
                            "Attributes": {
                                "HP": 100,
                                "Money": 0
                            }
                        }
                    ],
                    "Items": [
                        {
                            "Name": "Brushwood",
                            "Attributes": {
                                "Value": 1
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140557505853056"
                        },
                        {
                            "Destination": "140557505854528"
                        },
                        {
                            "Destination": "140557505853824"
                        },
                        {
                            "Destination": "140557505852992"
                        },
                        {
                            "Destination": "140557505868032"
                        }
                    ]
                },
                {
                    "Id": "140557505852992",
                    "Name": "Forest",
                    "Items": [
                        {
                            "Name": "Brushwood",
                            "Attributes": {
                                "Value": 1
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140557505867904"
                        },
                        {
                            "Destination": "140557505855168"
                        }
                    ]
                },
                {
                    "Id": "140557505868224",
                    "Name": "Forest",
                    "Items": [
                        {
                            "Name": "Brushwood",
                            "Attributes": {
                                "Value": 1
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140557505853824"
                        },
                        {
                            "Destination": "140557505868032"
                        }
                    ]
                },
                {
                    "Id": "140557505868032",
                    "Name": "Forest",
                    "Connections": [
                        {
                            "Destination": "140557505855168"
                        },
                        {
                            "Destination": "140557505868224"
                        },
                        {
                            "Destination": "140557505855232"
                        }
                    ]
                }
            ]
        },
        "RSide": {},
        "Instructions": []
    }
]

=== iwonagg/StoryGraphPhD/api_get_random_world_json/worlds/rumcajs-world_en.json
[
	{
	  "Title": "World around Jiczyn with english names / Świat wokół Jiczyna z angielskimi nazwami",
	  "TitleGeneric": "",
	  "Description": "Świat, w którym może wydarzyć się misja Rumcajsa.",
	  "Override": 0,
	  "LSide": {
		"Locations": [
		{
			"Name": "Cave",
			"Connections": [ { "Destination": "M23" } ],
			"Characters": [ { "Name": "Manka" } ]
		}, {
			"Name": "Jiczyn",
			"Connections": [ { "Destination": "M31" } ],
			"Characters": [
				{ "Name": "Merchant" },
				{ "Name": "Jeweler" }
			]
		}, {
			"Id": "M11",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M12" },
				{ "Destination": "M21" }
			]
		}, {
			"Id": "M12",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M11" },
				{ "Destination": "M13" },
				{ "Destination": "M22" }
			],
			"Items": [ { "Name": "Brushwood" } ]
		}, {
			"Id": "M13",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M12" },
				{ "Destination": "M14" },
				{ "Destination": "M23" }
			]
		}, {
			"Id": "M14",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M13" },
				{ "Destination": "M24" }
			],
			"Items": [ { "Name": "Brushwood" } ]
		}, {
			"Id": "M21",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M11" },
				{ "Destination": "M22" },
				{ "Destination": "M31" }
			]
		}, {
			"Id": "M22",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M12" },
				{ "Destination": "M21" },
				{ "Destination": "M23" },
				{ "Destination": "M32" }
			]
		}, {
			"Id": "M23",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "Cave" },
				{ "Destination": "M13" },
				{ "Destination": "M22" },
				{ "Destination": "M24" },
				{ "Destination": "M33" }
			],
			"Characters": [ { "Name": "Rumcajs" } ],
			"Items": [ { "Name": "Brushwood" } ]
		}, {
			"Id": "M24",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M14" },
				{ "Destination": "M23" },
				{ "Destination": "M34" }
			]
		}, {
			"Id": "M31",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "Jiczyn" },
				{ "Destination": "M21" },
				{ "Destination": "M32" },
				{ "Destination": "M41" }
			]
		}, {
			"Id": "M32",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M22" },
				{ "Destination": "M31" },
				{ "Destination": "M33" },
				{ "Destination": "M42" }
			]
		}, {
			"Id": "M33",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M23" },
				{ "Destination": "M32" },
				{ "Destination": "M34" },
				{ "Destination": "M43" }
			]
		}, {
			"Id": "M34",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M24" },
				{ "Destination": "M33" },
				{ "Destination": "M44" }
			],
			"Items": [ { "Name": "Brushwood" } ]
		}, {
			"Id": "M41",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M31" },
				{ "Destination": "M42" }
			]
		}, {
			"Id": "M42",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M32" },
				{ "Destination": "M41" },
				{ "Destination": "M43" }
			]
		}, {
			"Id": "M43",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M33" },
				{ "Destination": "M42" },
				{ "Destination": "M44" }
			]
		}, {
			"Id": "M44",
			"Name": "Forest",
			"Connections": [
				{ "Destination": "M34" },
				{ "Destination": "M43" }
			],
			"Items": [ { "Name": "Brushwood" } ]
		}
	]
},
"RSide": {},
"Instructions": []
}
]

=== iwonagg/StoryGraphPhD/api_get_random_world_json/worlds/produkcje_automatyczne_wygrywania.json
[
  {
    "Title": "DragonStory mission complited / Zakończenie sukcesem misji DragonStory",
    "TitleGeneric": "",
    "Description": "«Bohater» osiągnął cel misji.",
    "Comment": "Główny bohater musi być pierwszą wymienioną postacią",
    "Override": 0,
    "LSide": {
      "Locations": [
        {
          "Id": "Lokacja_A",
          "Attributes": {},
          "Characters": [
            {
              "Id": "Bohater",
              "IsObject": true,
              "Attributes": {},
              "Characters": [],
              "Items": [
                {
                  "Name": "Dragon_egg"
                }
              ]
            }
          ],
          "Items": []

        }
      ]
    },
    "RSide": {},
    "Instructions": [
      {
        "Op": "winning"
      }
    ]
  },
  {
      "Title": "RumcajsStory mission complited / Zakończenie sukcesem misji RumcajsStory",
      "TitleGeneric": "",
      "Description": "Rumcajs osiągnął cel misji.",
      "Comment": "Główny bohater musi być pierwszą wymienioną postacią",
      "Override": 0,
      "LSide": {
          "Locations": [
              {
                  "Name": "Jaskinia",
                  "Characters": [
                      {
                          "Name": "Rumcajs"

                      },
                      {
                          "Name": "Hanka",
                          "Items": [
                            {
                                "Name": "Korale"
                            }
                        ]
                      }
                  ]
              }
          ]
      },
      "RSide": {},
      "Instructions": [
        {
            "Op": "winning"
        }
      ]
  }
]

=== iwonagg/StoryGraphPhD/api_get_random_world_json/worlds/rumcajs-world.json
[
	{
	  "Title": "World_around_Jiczyn / Świat wokół Jiczyna",
	  "TitleGeneric": "",
	  "Description": "Świat, w którym może wydarzyć się misja Rumcajsa.",
	  "Override": 0,
	  "LSide": {
		"Locations": [
		{
			"Name": "Jaskinia",
			"Connections": [ { "Destination": "m23" } ],
			"Characters": [ { "Name": "Hanka" } ]
		}, {
			"Name": "Jiczyn",
			"Connections": [ { "Destination": "m31" } ],
			"Characters": [
				{ "Name": "Handlarz" },
				{ "Name": "Jubiler" }
			]
		}, {
			"Id": "m11",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m12" },
				{ "Destination": "m21" }
			]
		}, {
			"Id": "m12",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m11" },
				{ "Destination": "m13" },
				{ "Destination": "m22" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "m13",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m12" },
				{ "Destination": "m14" },
				{ "Destination": "m23" }
			]
		}, {
			"Id": "m14",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m13" },
				{ "Destination": "m24" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "m21",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m11" },
				{ "Destination": "m22" },
				{ "Destination": "m31" }
			]
		}, {
			"Id": "m22",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m12" },
				{ "Destination": "m21" },
				{ "Destination": "m23" },
				{ "Destination": "m32" }
			]
		}, {
			"Id": "m23",
			"Name": "Las",
			"Connections": [
				{ "Destination": "Jaskinia" },
				{ "Destination": "m13" },
				{ "Destination": "m22" },
				{ "Destination": "m24" },
				{ "Destination": "m33" }
			],
			"Characters": [ { "Name": "Rumcajs" } ],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "m24",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m14" },
				{ "Destination": "m23" },
				{ "Destination": "m34" }
			]
		}, {
			"Id": "m31",
			"Name": "Las",
			"Connections": [
				{ "Destination": "Jiczyn" },
				{ "Destination": "m21" },
				{ "Destination": "m32" },
				{ "Destination": "m41" }
			]
		}, {
			"Id": "m32",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m22" },
				{ "Destination": "m31" },
				{ "Destination": "m33" },
				{ "Destination": "m42" }
			]
		}, {
			"Id": "m33",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m23" },
				{ "Destination": "m32" },
				{ "Destination": "m34" },
				{ "Destination": "m43" }
			]
		}, {
			"Id": "m34",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m24" },
				{ "Destination": "m33" },
				{ "Destination": "m44" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}, {
			"Id": "m41",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m31" },
				{ "Destination": "m42" }
			]
		}, {
			"Id": "m42",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m32" },
				{ "Destination": "m41" },
				{ "Destination": "m43" }
			]
		}, {
			"Id": "m43",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m33" },
				{ "Destination": "m42" },
				{ "Destination": "m44" }
			]
		}, {
			"Id": "m44",
			"Name": "Las",
			"Connections": [
				{ "Destination": "m34" },
				{ "Destination": "m43" }
			],
			"Items": [ { "Name": "Chrust" } ]
		}
	]
},
"RSide": {},
"Instructions": []
}
]
