=== iwonagg/StoryGraphPhD/json_validation/json_schema/schemas/archived_schema/schema_updated_20220120.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://www.ztg.fais.uj.edu.pl/",
    "title": "StoryGraph",
    "description": "JSON Schema for productions.",
    "type": "array",
    "definitions": {
        "node": {
            "type": "object",
            "anyOf": [
                {"required": ["Name"]},
                {"required": ["Id"]}
            ],
            "properties": {
                "Name": {"type": "string"}, 
                "Id": {"type": "string"},
                "Comment": {"type": "string"},
                "IsObject": {"type": "boolean"},
                "Characters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                },
                "Items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                },
                "Narration": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/node"
                    }
                },
                "Connections": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "Destination": {"type": "string"},
                            "Attributes": {
                                "type": "object",
                                "patternProperties": {
                                    "^.*$": {
                                        "anyOf": [
                                            {"type": "string"},
                                            {"type": "boolean"},
                                            {"type": "integer"},
                                            {"type": "number"},
                                            {"type": "null"}
                                        ]
                                    }
                                },
                                "additionalProperties": false
                            }
                        },
                        "additionalProperties": false,
                        "required": ["Destination"]
                    }
                },
                "Attributes": {
                    "type": "object",
                    "patternProperties": {
                        "^.*$": {
                        "anyOf": [
                            {"type": "string"},
                            {"type": "boolean"},
                            {"type": "integer"},
                            {"type": "number"},
                            {"type": "null"}
                        ]
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "items": {
        "type": "object",
        "properties": {
            "Title": {"type": "string"},
            "TitleGeneric": {"type": "string"},
            "Description": {"type": "string"},
            "Override": {"type": "integer", "enum": [0, 1]},
            "Comment": {"type": "string"},
            "LSide": {
                "type": "object",
                "properties": {
                    "Locations": {
                        "type": "array",
                        "items": {
                            "anyOf": [
                                {"$ref": "#/definitions/node"}
                            ]
                        }
                    }
                },
                "additionalProperties": false,
                "required": ["Locations"]
            },
            "RSide": {
                "type": "object",
                "properties": {},
                "additionalProperties": false
            },
            "Preconditions": {
                "type": "array",
                "items": {
                    "anyOf": [
                        {
                            "type": "object",
                            "properties": {
                                "Cond": {"type": "string"}
                            },
                            "additionalProperties": false,
                            "required": ["Cond"]
                        }, 
                        {
                            "type": "object",
                            "required": ["Count"],
                            "anyOf": [
                                {"required": ["Min"]},
                                {"required": ["Max"]},
                                {"required": ["Min", "Max"]}
                            ],
                            "properties": {
                                "Count": {"type": "string"},
                                "Min": {"type": "number"},
                                "Max": {"type": "number"}
                            },
                            "additionalProperties": false
                        }
                    ]
                }
            },
            "Instructions": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "Op": {"type": "string", "enum": ["create", "delete", "move", "set", "unset", "add", "mul", "winning"]},
                        "In": {"type": "string"},
                        "To": {"type": "string"},
                        "Attribute": {"type": "string"},
                        "Expr": {"type": "string"},
                        "Value": {
                            "anyOf": [
                                {"type": "string"},
                                {"type": "boolean"},
                                {"type": "integer"},
                                {"type": "number"},
                                {"type": "null"}
                            ]    
                        },                    
                        "Characters": {"type": "string", "enum": ["prohibit", "move"]},
                        "Items": {"type": "string", "enum": ["prohibit", "move"]},
                        "Sheaf": {"type": "object"}
                    },
                    "allOf": [
                        {
                            "if": {"properties": {"Op": { "enum": ["set"] }}},
                            "then": { 
                                "required": ["Attribute"],
                                "anyOf": [
                                    {"required": ["Value"]},
                                    {"required": ["Expr"]}
                                ]
                             }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["add"] }}},
                            "then": { "required": ["Attribute", "Value"] }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["mul"] }}},
                            "then": { "required": ["Attribute", "Value"] }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["delete"] }}},
                            "then": { 
                                "anyOf": [
                                    {"required": ["Node"]},
                                    {"required": ["Nodes"]}
                                ],
                                "properties": {
                                    "Node": {"type": "string"},
                                    "Nodes": {"type": "string"}
                                }
                            }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["create"] }}},
                            "then": { 
                                "required": ["In"],
                                "anyOf": [
                                    {"required": ["Node"]},
                                    {"required": ["Sheaf"]}
                                ],
                                "properties": {
                                    "Node": {"$ref": "#/definitions/node"}
                                }
                            }
                        },
                        {
                            "if": {"properties": {"Op": { "enum": ["move"] }}},
                            "then": { 
                                "required": ["To"],
                                "anyOf": [
                                    {"required": ["Node"]},
                                    {"required": ["Nodes"]}
                                ],
                                "properties": {
                                    "Node": {"type": "string"},
                                    "Nodes": {"type": "string"}
                                }
                            }
                        }
                    ]
                },
                "additionalProperties": false,
                "required": ["Op"]
            }
        },
        "additionalProperties": false,
        "required": ["Title", "TitleGeneric", "Description", "LSide", "RSide", "Instructions", "Override"]
    }
}

=== iwonagg/StoryGraphPhD/examples/RumcajsStory/quest_RumcajsStory_close.json
[
	{
		"Title": "Picking up brushwood / Podnoszenie chrustu",
		"TitleGeneric": "Picking item up / Podniesienie przedmiotu",
		"Description": "Rumcajs zbiera chrust.",
		"Override": 0,
		"LSide": {
			"Locations": [
				{
					"Name": "Forest",
					"Characters": [
						{
							"Name": "Rumcajs",
							"IsObject": true
						}
					],
					"Items": [
						{
							"Name": "Brushwood"
						}
					]
				}
			]
		},
		"RSide": {},
		"Instructions": [
			{
				"Op": "move",
				"Nodes": "Brushwood",
				"To": "Rumcajs/Items"
			}
		]
	},
	{
		"Title": "Selling the brushwood to Merchant / Sprzedaż chrustu handlarzowi",
		"TitleGeneric": "",
		"Comment": "Podejście drastycznie różne od transakcji kupna-sprzedaży",
		"Description": "Rumcajs sprzedaje chrust handlarzowi.",
		"Override": 0,
		"LSide": {
			"Locations": [
				{
					"Name": "Jiczyn",
					"Characters": [
						{
							"Name": "Rumcajs",
							"IsObject": true,
							"Items": [
								{
									"Name": "Brushwood"
								}
							]
						},
						{
							"Name": "Merchant"
						}
					]
				}
			]
		},
		"RSide": {},
		"Instructions": [
			{
				"Op": "delete",
				"Nodes": "Brushwood"
			},
			{
				"Op": "create",
				"In": "Rumcajs/Items",
				"Sheaf": {
					"Name": "Coin"
				}
			}
		]
	},
	{
		"Title": "Buying the necklace made by jeweler / Kupno korali stworzonych przez jubilera",
		"TitleGeneric": "",
		"Comment": "Podejście drastycznie różne od transakcji kupna-sprzedaży",
		"Description": "Jubiler tworzy korale i przekazuje je Rumcajsowi, który poświęca na nie miedziaki.",
		"Override": 0,
		"LSide": {
			"Locations": [
				{
					"Name": "Jiczyn",
					"Characters": [
						{
							"Name": "Rumcajs",
							"IsObject": true,
							"Items": [
								{
									"Id": "I1",
									"Name": "Coin"
								},
								{
									"Id": "I2",
									"Name": "Coin"
								},
								{
									"Id": "I3",
									"Name": "Coin"
								}
							]
						},
						{
							"Name": "Jeweler"
						}
					]
				}
			]
		},
		"RSide": {},
		"Instructions": [
			{
				"Op": "delete",
				"Nodes": "I1"
			},
			{
				"Op": "delete",
				"Nodes": "I2"
			},
			{
				"Op": "delete",
				"Nodes": "I3"
			},
			{
				"Op": "create",
				"In": "Rumcajs/Items",
				"Sheaf": {
					"Name": "Necklace"
				}
			}
		]
	},
	{
		"Title": "Giving the necklace to Manka / Ofiarowanie Hance korali",
		"TitleGeneric": "Item acquisition from another character / Przejęcie przedmiotu od innej postaci",
		"Description": "Rumcajs ofiarowuje korale ukochanej.",
		"Override": 0,
		"LSide": {
			"Locations": [
				{
					"Name": "Cave",
					"Characters": [
						{
							"Name": "Rumcajs",
							"IsObject": true,
							"Items": [
								{
									"Name": "Necklace"
								}
							]
						},
						{
							"Name": "Manka"
						}
					]
				}
			]
		},
		"RSide": {},
		"Instructions": [
			{
				"Op": "move",
				"Nodes": "Necklace",
				"To": "Manka/Items"
			}
		]
	},
	{
		"Title": "Rumcajs location change / Zmiana lokacji przez Rumcajsa",
		"TitleGeneric": "Location change / Zmiana lokacji",
		"Description": "Rumcajs przechodzi z lokacji «Anywhere» do lokacji «Loc2».",
		"Override": 0,
		"LSide": {
			"Locations": [
				{ "Id": "Anywhere",
					"Connections": [
						{
							"Destination": "Loc2"
						}
					],
					"Characters": [
						{
							"Name": "Rumcajs",
							"IsObject": true
						}
					]
				},
				{
					"Id": "Loc2"
				}
			]
		},
		"RSide": {},
		"Instructions": [
			{
				"Op": "move",
				"Nodes": "Rumcajs",
				"To": "Loc2/Characters"
			}
		]
	}
]

=== iwonagg/StoryGraphPhD/examples/DragonStory/world_DragonStory.json
[
    {
        "Title": "World_q0 / Świat_q0",
        "TitleGeneric": "",
        "Description": "Swiat, w którym może wydarzyć się misja DragonStory.",
        "Override": 0,
        "LSide": {
            "Locations": [
                {
                    "Id": "140686910713664",
                    "Name": "Road",
                    "Characters": [
                        {
                            "Name": "Main_hero",
                            "Items": [
                                {
                                    "Name": "Sword",
                                    "Attributes": {
                                        "Value": 1000
                                    }
                                }
                            ],
                            "Attributes": {
                                "HP": 100,
                                "Money": 10
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140686910711488"
                        },
                        {
                            "Destination": "140686910678976"
                        },
                        {
                            "Destination": "140686910277632"
                        },
                        {
                            "Destination": "140686911964288"
                        },
                        {
                            "Destination": "140686910710080"
                        }
                    ]
                },
                {
                    "Id": "140686910710080",
                    "Name": "Wizards_hut",
                    "Attributes": {
                        "IsPrivate": true
                    },
                    "Characters": [
                        {
                            "Name": "Wizard",
                            "Attributes": {
                                "HP": 200,
                                "Money": 100,
                                "IsAuthority": true
                            }
                        }
                    ],
                    "Items": [
                        {
                            "Name": "Elixir",
                            "Attributes": {
                                "Value": 10,
                                "NutritionalValue": 1000
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140686910713664"
                        }
                    ]
                },
                {
                    "Id": "140686910655872",
                    "Name": "Dragons_lair",
                    "Characters": [
                        {
                            "Name": "Dragon",
                            "Attributes": {
                                "HP": 1000
                            }
                        }
                    ],
                    "Items": [
                        {
                            "Name": "Dragon_egg",
                            "Attributes": {
                                "Value": 4000
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140686910711488"
                        }
                    ]
                },
                {
                    "Id": "140686910711488",
                    "Name": "Forest",
                    "Items": [
                        {
                            "Name": "Herbs",
                            "Attributes": {
                                "Value": 30,
                                "IsPoison": true
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140686910713664"
                        },
                        {
                            "Destination": "140686910655872"
                        }
                    ]
                },
                {
                    "Id": "140686910277632",
                    "Name": "Pasture",
                    "Characters": [
                        {
                            "Name": "Sheep",
                            "Attributes": {
                                "HP": 10,
                                "NutritionalValue": 20
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140686910713664"
                        },
                        {
                            "Destination": "140686911964288"
                        }
                    ]
                },
                {
                    "Id": "140686911964288",
                    "Name": "Village",
                    "Items": [
                        {
                            "Name": "Well"
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140686910713664"
                        },
                        {
                            "Destination": "140686910277632"
                        }
                    ]
                },
                {
                    "Id": "140686910678976",
                    "Name": "Inn",
                    "Characters": [
                        {
                            "Name": "Innkeeper",
                            "Items": [
                                {
                                    "Name": "Poison",
                                    "Attributes": {
                                        "Value": 1000,
                                        "IsPoison": true
                                    }
                                }
                            ],
                            "Attributes": {
                                "HP": 100,
                                "Money": 1200
                            }
                        },
                        {
                            "Name": "Drunkard",
                            "Items": [
                                {
                                    "Name": "Alcohol",
                                    "Attributes": {
                                        "Value": 3,
                                        "NutritionalValue": 1,
                                        "IsRotten": true
                                    }
                                }
                            ],
                            "Attributes": {
                                "HP": 100,
                                "Money": 0,
                                "IsTroublemaker": true
                            }
                        }
                    ],
                    "Connections": [
                        {
                            "Destination": "140686910713664"
                        },
                        {
                            "Destination": "140686910277632"
                        }
                    ]
                },
                {
                    "Name": "Prison",
                    "Characters": [
                        
                    ],
                    "Connections": [
                        {
                            "Destination": "Road"
                        }
                    ]
                }
            ]
        },
        "RSide": {},
        "Instructions": []
    }
]

=== iwonagg/StoryGraphPhD/examples/produkcje_automatyczne_wygrywania.json
[
  {
    "Title": "DragonStory mission complited / Zakończenie sukcesem misji DragonStory",
    "TitleGeneric": "",
    "Description": "«Bohater» osiągnął cel misji.",
    "Comment": "Główny bohater musi być pierwszą wymienioną postacią",
    "Override": 0,
    "LSide": {
      "Locations": [
        {
          "Id": "Lokacja_A",
          "Attributes": {},
          "Characters": [
            {
              "Id": "Bohater",
              "IsObject": true,
              "Attributes": {},
              "Characters": [],
              "Items": [
                {
                  "Name": "Dragon_egg"
                }
              ]
            }
          ],
          "Items": []

        }
      ]
    },
    "RSide": {},
    "Instructions": [
      {
        "Op": "winning"
      }
    ]
  },
  {
      "Title": "RumcajsStory mission complited pl / Zakończenie sukcesem misji RumcajsStory pl",
      "TitleGeneric": "",
      "Description": "Rumcajs osiągnął cel misji.",
      "Comment": "Główny bohater musi być pierwszą wymienioną postacią",
      "Override": 0,
      "LSide": {
          "Locations": [
              {
                  "Name": "Jaskinia",
                  "Characters": [
                      {
                          "Name": "Rumcajs"

                      },
                      {
                          "Name": "Hanka",
                          "Items": [
                            {
                                "Name": "Korale"
                            }
                        ]
                      }
                  ]
              }
          ]
      },
      "RSide": {},
      "Instructions": [
        {
            "Op": "winning"
        }
      ]
  },
  {
      "Title": "RumcajsStory mission complited en / Zakończenie sukcesem misji RumcajsStory en",
      "TitleGeneric": "",
      "Description": "Rumcajs osiągnął cel misji.",
      "Comment": "Główny bohater musi być pierwszą wymienioną postacią",
      "Override": 0,
      "LSide": {
          "Locations": [
              {
                  "Name": "Cave",
                  "Characters": [
                      {
                          "Name": "Rumcajs"

                      },
                      {
                          "Name": "Manka",
                          "Items": [
                            {
                                "Name": "Necklace"
                            }
                        ]
                      }
                  ]
              }
          ]
      },
      "RSide": {},
      "Instructions": [
        {
            "Op": "winning"
        }
      ]
  }
]

=== iwonagg/StoryGraphPhD/examples/DragonStory/quest_DragonStory.json
[
    {
    "Title": "Drunkard gets thrown out of Inn / Wyrzucenie awanturnika z karczmy",
    "TitleGeneric": "Fight ending with character’s escape / Walka zakończona ucieczką uczestnika",
    "Description": "W karczmie awanturuje się pijak. Wzbudza to irytację bohatera, który po ojcowsku daje mu w ucho i zaskoczony pijak wybiega na zewnątrz. Karczmarz wzdycha z ulgą i obdarza bohatera wdzięcznym spojrzeniem.",
    "Override": 0,
    "LSide": {
      "Locations": [
        {
          "Name": "Inn",
          "Characters": [
            {
              "Name": "Main_hero",
              "IsObject": true,
              "Attributes": {}
            },
            {
              "Name": "Innkeeper",
              "Items": [
                {
                  "Name": "Poison",
                  "Attributes": {}
                }

              ]
            },
            {
              "Name": "Drunkard",
              "Attributes": {
                "IsTroublemaker": true
              },
              "Items": []
            }
          ],
          "Items": [],
          "Connections": [
            {
              "Destination": "Road"
            }
          ]
        },
        {
          "Name": "Road"
          
        }
      ]
    },
    "RSide": {},
    "Instructions": [
      {
        "Op": "move",
        "Nodes": "Drunkard/Items/*",
        "To": "Inn/Items"
      },
      {
        "Op": "move",
        "Nodes": "Drunkard",
        "To": "Road/Characters"
      },
      {
        "Op": "create",
        "In": "Main_hero/Narration",
        "Sheaf": {
          "Name": "Innkeepers_gratitude",
          "Attributes": {
            "Knowledge": "Karczmarz jest Ci winien wdzięczność.",
            "Level": 1
          }
        }
      }
    ]
  },
  {
    "Title": "Obtaining poison / Zdobycie trucizny",
    "TitleGeneric": "Item acquisition from another character / Przejęcie przedmiotu od innej postaci",
    "Description": "Bohater i karczmarz znajdują się w karczmie. W dowód wdzięczności karczmarz przekazuje bohaterowi truciznę, co wyrównuje rachunki.",
    "Override": 0,
    "LSide": {
      "Locations": [
        {
          "Name": "Inn",
          "Characters": [
            {
              "Name": "Main_hero",
              "IsObject": true,
              "Narration": [
                {
                  "Name": "Innkeepers_gratitude",
                  "Attributes": {
                    "Level": null
                  }
                }
              ],
              "Items": []
            },
            {
              "Name": "Innkeeper",
              "Items": [
                {
                  "Name": "Poison"
                }
              ]
            }
          ]
        }
      ]
    },
    "RSide": {},
    "Preconditions": [
      {
        "Cond": "Innkeepers_gratitude.Level >= 1"
      }
    ],
    "Instructions": [
      {
        "Op": "move",
        "Nodes": "Poison",
        "To": "Main_hero/Items"
      },
      {
        "Op": "set",
        "Attribute": "Innkeepers_gratitude.Level",
        "Expr": "Innkeepers_gratitude.Level - 1"
      }
    ]
  },
  {
    "Title": "Wizard receives a distress call from Main hero / Bohater wzywa czarodzieja na pomoc",
    "TitleGeneric": "Teleportation / Teleportacja",
    "Description": "Studnia w wiosce jest zatruta. Wezwany czarodziej przybywa z lokacji «Anywhere» do wioski, żeby uzdatnić studnię.",
    "Comment": "Gdy będą gotowe diagramy sterujące NPC można będzie zamienić tą produkcję na „Wizard's location change after well poisoning”, czyli produkcję, której podniotem jest czarodziej a nie bohater.",
    "Override": 0,
    "LSide": {
      "Locations": [
        {
          "Name": "Village",
          "Characters": [
            {
              "Name": "Main_hero",
              "IsObject": true
            }
          ],
          "Items": [
            {
              "Name": "Well",
              "Attributes": {
                "IsPoison": true
              }
            }
          ]
        },
        {
          "Id": "Anywhere",
          "Characters": [
            {
              "Name": "Wizard"
            }
          ]
        }
      ]
    },
    "RSide": {},
    "Instructions": [
      {
        "Op": "move",
        "Nodes": "Wizard",
        "To": "Village/Characters"
      }
    ]
  }
]
